version: '3'

services:
    post:
        build: .
        tty: true
        image: senryu/post
        hostname: post
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        # read_only: true
        volumes:
            - .:/go/src/github.com/yu-yagishita/senryu-post
        ports:
            - "8081:8080"
        networks:
            - shared-network
    post-db:
        build:
            context: ./docker/post-db/
        image: senryu/post-db
        hostname: post-db
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid
        environment:
            - reschedule=on-node-failure
        ports:
            - "27018:27017"
        networks:
            - shared-network
networks:
    shared-network:
        external: true
